title: "Molecular Cell Biomechanics Laboratory"
description: "Computational Biology Research Group"
url: "https://atamadon.github.io"
theme: minima

permalink: pretty

collections:
  team:
    output: false
  publications:
    output: false

exclude:
  - lib
  - scripts
  - test
  - vendor

sass:
  style: compressed

# defaults:
#   - scope:
#       path: "_publications"
#     values:
#       layout: default
#       permalink: "/publications/:basename/"
