title: "Molecular Cell Biomechanics Laboratory"
description: "Computational Biology Research Group"
theme: minima

permalink: pretty

collections:
  team:
    output: false
  publications:
    output: false

# defaults:
#   - scope:
#       path: "_publications"
#     values:
#       layout: default
#       permalink: "/publications/:basename/"