title: "Molecular Cell Biomechanics Laboratory"
description: "Computational Biology Research Group"
theme: minima

url: "https://atamadon.githb.io"
baseurl: "/lab-website"
permalink: pretty

collections:
  team:
    output: false
  publications:
    output: false
